spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/portal_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: click123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    producer:
      max-request-size: 20971520

server:
  port: 8081
  forward-headers-strategy: native

springdoc:
  use-management-port: false
  show-actuator: false
  api-docs:
    enabled: true
    path: /v3/api-docs
    server-url: http://127.0.0.1:8080/auth-service
  default-produces-media-type: application/json
  override-with-generic-response: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  paths-to-match: "/**"

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_A_EXPIRATION}

hashid:
  salt: 9VlqvY6RA4GJqqoDtV7RKhypGogOVB+v3BnpTYWOMglgFo3TWNOaJ5W9Zfw0YOeckqCdRoezuXTk+hqCLiZrHg==
  min-length: 8

app:
  jwt:
    refresh-token-duration-ms: 604800000
